import { readArrivalSequence, readProjectEvidence } from './evidence';
import type { CalendarEvent, Source, SourceAttachment, SourceItem } from '../src/shared/types';

const ARCHIVE_START = Date.parse('2026-09-08T13:00:00Z');
const providers: Source[] = ['gmail', 'slack', 'discord', 'linear', 'asana', 'calendar', 'imessage'];

interface Project {
  id: string; name: string; code: string; owner: string; analyst: string; engineer: string;
  product: string; milestone: string; adopted: number; eligible: number; previousTickets: number;
  tickets: number; budget: number; spent: number; risk: string; decision: string;
  customers: string[]; measures: string[]; closedIssue: string; nextStep: string;
}

const projects: Project[] = [
  { id: 'pinecone', name: 'Pinecone Commerce', code: 'PIN', owner: 'Nora Feld', analyst: 'Eli Navarro', engineer: 'Mina Park', product: 'merchant checkout launch', milestone: 'leadership launch review', adopted: 170, eligible: 250, previousTickets: 31, tickets: 18, budget: 48000, spent: 31200, risk: 'Seven merchant migrations still require named owners to confirm completion.', decision: 'Keep the staged rollout at 68% until migration owners finish their checks.', customers: ['Birch Books', 'Copper Coffee', 'Poppy Goods', 'Juniper Bikes', 'Fern Market', 'Oak Paper', 'Willow Studio'], measures: ['activated merchants', 'eligible merchants', 'support tickets'], closedIssue: 'PIN-172 receipt footer clipped on narrow screens', nextStep: 'Collect migration confirmations before expanding checkout access.' },
  { id: 'harbor', name: 'Harbor Health', code: 'HBR', owner: 'Dr. Leah Moss', analyst: 'Tessa Ng', engineer: 'Ravi Patel', product: 'clinic appointment reminder pilot', milestone: 'front desk pilot review', adopted: 84, eligible: 120, previousTickets: 24, tickets: 11, budget: 36000, spent: 21900, risk: 'Two clinics have not signed off on translated reminder copy.', decision: 'Use appointment counts only; keep patient names out of the pilot readout.', customers: ['East Quay Clinic', 'Pier Family Practice', 'Bay Walk Clinic', 'Mariner Pediatrics', 'Anchor Community Care', 'Tide Street Clinic', 'Seaport Practice'], measures: ['reminders delivered', 'scheduled reminders', 'front desk questions'], closedIssue: 'HBR-206 reminder preview timezone label', nextStep: 'Ask clinic coordinators to approve Spanish reminder copy.' },
  { id: 'juniper', name: 'Juniper Library', code: 'LIB', owner: 'Marta Bell', analyst: 'Owen Price', engineer: 'Jules Tran', product: 'library room reservation service', milestone: 'branch coordinator check-in', adopted: 63, eligible: 90, previousTickets: 19, tickets: 8, budget: 22000, spent: 14700, risk: 'The West Branch kiosk remains offline during network repairs.', decision: 'Retain phone booking at West Branch until its kiosk reconnects.', customers: ['Central Branch', 'West Branch', 'Hill Branch', 'Elm Branch', 'River Branch', 'Market Branch', 'College Branch'], measures: ['online reservations', 'available reservations', 'booking questions'], closedIssue: 'LIB-118 duplicate reservation receipt subject', nextStep: 'Compare room utilization after the Saturday reading clubs.' },
  { id: 'beacon', name: 'Beacon Grid', code: 'BG', owner: 'Amir Khan', analyst: 'Sofia Reed', engineer: 'Chen Wu', product: 'building energy dashboard', milestone: 'facilities budget review', adopted: 39, eligible: 60, previousTickets: 16, tickets: 9, budget: 75000, spent: 46200, risk: 'Meter feeds from two buildings arrive a day late.', decision: 'Show stale readings with a date badge instead of estimating usage.', customers: ['Beacon Tower', 'Canal House', 'Foundry Hall', 'Station Annex', 'Stone Yard', 'Waterfront Hub', 'Park Offices'], measures: ['connected meters', 'planned meters', 'facilities questions'], closedIssue: 'BG-309 legend colors repeated in export', nextStep: 'Reconcile daily meter totals against the facilities CSV.' },
  { id: 'maple', name: 'Maple School', code: 'MAP', owner: 'Grace Wilson', analyst: 'Isaac Lee', engineer: 'Anika Roy', product: 'after-school club enrollment', milestone: 'family services review', adopted: 112, eligible: 160, previousTickets: 28, tickets: 12, budget: 18000, spent: 10500, risk: 'Robotics and ceramics are close to room capacity.', decision: 'Keep a dated waitlist and avoid promising a place until a seat opens.', customers: ['Robotics', 'Ceramics', 'Chess', 'Garden Club', 'Choir', 'Running Club', 'Book Club'], measures: ['confirmed enrollments', 'available places', 'family questions'], closedIssue: 'MAP-88 missing club location in confirmation', nextStep: 'Compare attendance with enrollment before opening more places.' },
  { id: 'northstar', name: 'Northstar Studio', code: 'NS', owner: 'Theo Grant', analyst: 'Freya Cole', engineer: 'Ben Alvarez', product: 'client asset review portal', milestone: 'campaign production review', adopted: 46, eligible: 80, previousTickets: 21, tickets: 10, budget: 54000, spent: 33750, risk: 'Print proofs are awaiting legal approval for the spring campaign.', decision: 'Separate approved digital artwork from print files still under review.', customers: ['Alto Audio', 'Cedar Travel', 'Drift Apparel', 'Ember Tea', 'Field Supply', 'Grove Hotels', 'Halo Watches'], measures: ['approved assets', 'submitted assets', 'review questions'], closedIssue: 'NS-144 filename truncation in review list', nextStep: 'Collect legal sign-off before sending print proofs to the vendor.' },
  { id: 'orchard', name: 'Orchard Cooperative', code: 'ORC', owner: 'Rosa Silva', analyst: 'Miles Cook', engineer: 'Nia James', product: 'weekly produce box subscriptions', milestone: 'grower delivery review', adopted: 156, eligible: 200, previousTickets: 35, tickets: 15, budget: 27000, spent: 18300, risk: 'Heavy rain may reduce the tomato allocation next week.', decision: 'Offer squash as a substitute only after customers see the box contents.', customers: ['Apple Ridge Farm', 'Blue Barn Growers', 'Creekside Produce', 'Dawn Orchards', 'Evergreen Acres', 'Fox Hollow Farm', 'Green Lane'], measures: ['confirmed boxes', 'box capacity', 'delivery questions'], closedIssue: 'ORC-57 pickup address missing suite number', nextStep: 'Reconcile packing counts before sending the pickup reminder.' },
  { id: 'metro', name: 'Metro Mobility', code: 'MET', owner: 'Dante Brooks', analyst: 'Asha Das', engineer: 'Leo Kim', product: 'bike station service dashboard', milestone: 'depot maintenance review', adopted: 52, eligible: 75, previousTickets: 26, tickets: 13, budget: 62000, spent: 40800, risk: 'The canal depot has only one spare battery shipment this week.', decision: 'Prioritize commuter stations with repeated morning outages.', customers: ['Canal Depot', 'Market Station', 'Elm Junction', 'Harbor Gate', 'University Loop', 'Central Plaza', 'Park Entrance'], measures: ['healthy stations', 'tracked stations', 'maintenance tickets'], closedIssue: 'MET-231 service map tooltip blocks station link', nextStep: 'Check depot stock before assigning the weekend repair route.' },
  { id: 'lumen', name: 'Lumen Museum', code: 'LUM', owner: 'Hazel Wright', analyst: 'Finn Murphy', engineer: 'Ada Chen', product: 'member exhibition booking', milestone: 'visitor services briefing', adopted: 91, eligible: 140, previousTickets: 23, tickets: 7, budget: 31000, spent: 19250, risk: 'Saturday access tours need an additional trained volunteer.', decision: 'Keep step-free tour slots reserved until the access coordinator approves release.', customers: ['Light Lab', 'Archive Room', 'Sculpture Hall', 'Print Gallery', 'East Wing', 'Learning Studio', 'Roof Garden'], measures: ['member bookings', 'released slots', 'visitor questions'], closedIssue: 'LUM-93 mobile pass date wraps incorrectly', nextStep: 'Confirm volunteer coverage before increasing tour capacity.' },
  { id: 'cedar', name: 'Cedar Kitchen', code: 'CDR', owner: 'Olivia Hart', analyst: 'Noah Stone', engineer: 'Zoe Park', product: 'community meal collection planner', milestone: 'volunteer kitchen briefing', adopted: 128, eligible: 180, previousTickets: 32, tickets: 14, budget: 24000, spent: 16800, risk: 'The oven inspection overlaps the Wednesday batch preparation.', decision: 'Keep allergy notes in the kitchen roster and out of the public pickup sheet.', customers: ['North Hall', 'Cedar Center', 'Union Shelter', 'Park Pantry', 'Elm House', 'River Table', 'West Hub'], measures: ['reserved meals', 'meal capacity', 'pickup questions'], closedIssue: 'CDR-64 collection window absent from printed slip', nextStep: 'Move Wednesday preparation to the small kitchen if inspection runs late.' },
];

function attachment(id: string, name: string, content: string): SourceAttachment {
  return { id, name, content, mediaType: name.endsWith('.csv') ? 'text/csv' : name.endsWith('.json') ? 'application/json' : 'text/markdown' };
}

function files(project: Project): SourceAttachment[] {
  return [
    ['metrics', 'weekly-metrics.csv'], ['owners', 'owner-register.csv'],
    ['brief', 'project-brief.md'], ['decisions', 'decisions.md'],
    ['budget', 'budget.csv'], ['release', 'release-notes.md'],
    ['agenda', 'review-agenda.md'], ['manifest', 'evidence-index.json'],
  ].map(([id, suffix]) => {
    const name = `${project.code.toLowerCase()}-${suffix}`;
    return attachment(`${project.id}-${id}`, name, readProjectEvidence(project.id, name));
  });
}

function historicalMessages(p: Project): Array<[string, string]> {
  return [
    ['Project scope agreed', `${p.owner}: We agreed the scope for the ${p.product}. The next checkpoint is the ${p.milestone}. The attached brief is the reference for this project.`],
    ['Weekly counts filed', `${p.analyst}: The archive export records ${p.adopted} of ${p.eligible} ${p.measures[0]}. We had ${p.tickets} ${p.measures[2]}, down from ${p.previousTickets}. Figures are in the attached CSV.`],
    ['Owner register checked', `${p.owner}: All seven organizations have a named owner in the register. ${p.risk} This is the archived review record.`],
    ['Budget reconciled', `Finance matched the invoices for ${p.name}. We spent $${p.spent.toLocaleString('en-US')} against an approved $${p.budget.toLocaleString('en-US')}. No purchase or payment is requested.`],
    ['Decision notes filed', `${p.owner}: The accepted decision is recorded: ${p.decision} The next checkpoint remains ${p.nextStep}`],
    ['Previous release signed off', `${p.engineer}: ${p.closedIssue} is closed. The reporter verified the correction in the previous release. The attached notes state the scope of that test.`],
    ['Review agenda archived', `The ${p.milestone} agenda is attached for reference. The meeting happened earlier this month. This is a copy of the agenda, not a new meeting invitation.`],
    ['Evidence index published', `${p.analyst}: The evidence index lists the metrics, owner register, and prior release notes for ${p.code}. Use the project identifier when citing these records.`],
    ['Operations handover', `${p.owner} handed the ${p.product} morning checks to ${p.analyst}. ${p.engineer} remains the engineering contact. The handover was completed during the previous review.`],
    ['First organization check-in', `${p.customers[0]} confirmed receipt of the ${p.name} briefing. Their contact had no further questions after the walkthrough.`],
    ['Second organization notes', `${p.customers[1]} asked whether the review would include ${p.measures[2]}. ${p.analyst} already answered yes and pointed them to the weekly export. Conversation closed.`],
    ['Training attendance', `${p.customers[2]} and ${p.customers[3]} attended the recorded ${p.product} training. Slides and attendance were filed by ${p.owner}. No follow-up was requested.`],
    ['Archived support trend', `${p.analyst}: The previous baseline was ${p.previousTickets} ${p.measures[2]}. The current archive shows ${p.tickets}. This comparison belongs to ${p.code}; it should not be copied into another project's report.`],
    ['Risk accepted for review', `The review retained this open risk: ${p.risk} ${p.owner} will discuss it at the next planned checkpoint. This message records the earlier review decision.`],
    ['Working agreement', `${p.engineer}: When discussing ${p.name}, include ${p.code} in the subject. The ${p.closedIssue.split(' ')[0]} thread is closed; new failures should have their own reproduction and date.`],
    ['Receipt confirmed', `${p.owner}: Thanks, I have the ${p.name} metrics and the owner register. The files opened correctly. Nothing else needed today.`],
    ['Community note', `A participant from ${p.customers[4]} liked the clearer ${p.product} instructions. They were sharing feedback, not asking for a redesign.`],
    ['Archive retention', `Operations retained the ${p.code} review files with the weekly export. The approved budget is $${p.budget}; invoices are already reconciled. This is an archive notice.`],
    ['Accessibility review closed', `${p.customers[5]} checked the large-text instructions for ${p.name}. The earlier formatting issue was resolved, and they confirmed the final version.`],
    ['Office hours recap', `${p.analyst} answered two questions from ${p.customers[6]} about ${p.measures[0]}. Both answers are now in the project brief. There are no unanswered questions in this conversation.`],
    ['Review minutes approved', `${p.owner} approved the earlier ${p.milestone} minutes. Accepted decision: ${p.decision} The minutes are final.`],
    ['Delivery receipt', `The ${p.name} evidence bundle reached ${p.owner} and ${p.engineer}. This automatic delivery receipt confirms a completed handoff.`],
    ['Earlier request withdrawn', `${p.owner}: Please disregard my earlier request for a separate ${p.code} summary. I used the existing review notes and no longer need another document.`],
    ['Resolved issue reminder', `${p.closedIssue} remains closed. This automatic issue summary repeats the resolution from last week; no new reproduction or regression is reported.`],
    ['Photo from the walkthrough', `${p.customers[0]} shared a photo after the ${p.name} walkthrough and thanked ${p.analyst}. No action requested.`],
    ['Definitions clarified', `For ${p.code}, the numerator is ${p.measures[0]} and the denominator is ${p.measures[1]}. ${p.analyst} confirmed that ${p.adopted}/${p.eligible} uses the same reporting window.`],
    ['Spending explanation', `${p.owner}: The $${p.spent} spent includes implementation, operations, and training. The attached budget from the earlier thread is authoritative; avoid treating the approved $${p.budget} as money already spent.`],
    ['Completed reminder', `The reminder for the previous ${p.milestone} has expired. The meeting was held and its minutes were approved. No new event should be created from this archive notice.`],
    ['Engineering contact', `${p.engineer} is the owner for technical questions about ${p.product}. ${p.owner} approves changes to scope. This is a saved contact note.`],
    ['Closed checklist', `${p.analyst} completed the previous ${p.code} weekly checklist: reconciled metrics, checked the register, and filed the meeting notes. No checklist items remain from that week.`],
    ['Newsletter subscription confirmed', `You are subscribed to the ${p.name} monthly update. The next edition will cover the ${p.product}. This automatic confirmation does not require a reply.`],
    ['Reporting boundary', `${p.owner}: ${p.name} and Pinecone Commerce have separate budgets and customer populations. A similar request for a readout does not make them the same piece of work.`],
    ['Correction to an old address', `${p.customers[3]} corrected the office mailing address in the archived contact register. Operations has already applied the change. No calendar or shipping action is outstanding.`],
    ['Meeting declined and closed', `${p.engineer} declined the optional retrospective because the notes covered their questions. The organizer accepted the decline; no replacement meeting is needed.`],
    ['Support queue reconciled', `${p.analyst} checked that the archived ${p.tickets} support count belongs to ${p.name}. The support export and the review notes agree for this period.`],
    ['Scope question answered', `${p.customers[2]} asked whether the ${p.product} included an extra location. ${p.owner} answered that the approved scope is the seven organizations in the register. They accepted the answer.`],
    ['Friday sign-off', `${p.owner}: All documents from the earlier ${p.milestone} are filed. The open project risk is still documented separately: ${p.risk}`],
    ['Automated backup notice', `The ${p.code} archive backup completed successfully. Eight evidence files passed checksum verification. This is a system notification.`],
    ['Thank-you note', `${p.customers[6]}: Thanks to ${p.engineer} for explaining the ${p.product} changes. We have what we need for the next internal review.`],
    ['Old draft superseded', `${p.analyst}: The first ${p.name} draft used preliminary counts. It was superseded by the CSV with ${p.adopted} and ${p.eligible}. Do not resurrect the preliminary version.`],
    ['Planning note filed', `Earlier planning note for ${p.code}: ${p.nextStep} The owner is ${p.owner}. This note was saved as background for the next review, not assigned as a new task.`],
    ['Resolved discussion locked', `The conversation about ${p.closedIssue.split(' ')[0]} was locked after the reporter confirmed the fix. Further replies are archived; there is no new failure here.`],
    ['Weekly digest delivered', `The weekly ${p.name} digest was delivered to ${p.owner}. It included ${p.adopted}/${p.eligible} adoption, ${p.tickets} questions, and the open project risk. Delivery succeeded.`],
    ['No change to our appointment', `${p.customers[1]}: We will keep the appointment already on the calendar. There is no change of date, time, attendees, or location.`],
    ['Archive complete', `${p.analyst}: This closes the previous ${p.name} reporting period. The next review can cite the metrics and owner register, but any new request should be evaluated on its own wording.`],
  ];
}

export function initialSources(): SourceItem[] {
  return projects.flatMap((project, projectIndex) => {
    const attachments = files(project);
    return historicalMessages(project).map(([title, content], index) => {
      const source = providers[(projectIndex * 45 + index) % providers.length];
      const topic = Math.floor(index / 3);
      return {
        id: `history-${project.id}-${String(index + 1).padStart(2, '0')}`, source,
        externalId: `${source}-${project.code}-archive-${index + 1}`,
        threadId: `${source}:${project.code}:archive:${topic}`,
        author: index % 3 === 0 ? project.owner : index % 3 === 1 ? project.analyst : project.engineer,
        title: `${project.code} · ${title}`, content: `${project.name} / ${project.code}\n\n${content}`,
        timestamp: ARCHIVE_START + index * 30 * 60_000 + projectIndex * 60_000,
        ...(source === 'slack' || source === 'discord' ? { channel: `#${project.id}-${source === 'slack' ? 'team' : 'community'}` } : {}),
        disposition: 'ignored' as const, reason: 'Historical context',
        ...(index < attachments.length ? { attachments: [attachments[index === 1 ? 0 : index === 0 ? 2 : index === 2 ? 1 : index === 3 ? 4 : index === 4 ? 3 : index]] } : {}),
      };
    });
  });
}

function dinnerTime(now: number, hour: number, minute: number): string {
  const date = new Date(now);
  date.setDate(date.getDate() + 2);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
}

function dated(now: number): string {
  return new Date(dinnerTime(now, 19, 30)).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
}

export function initialCalendar(now: number): CalendarEvent[] {
  return [{ id: 'calendar-focus', title: 'Pinecone release focus', start: dinnerTime(now, 9, 0), end: dinnerTime(now, 11, 0), attendees: ['mina@example.test'], location: 'Office', description: 'Fictional calendar block reserved for PIN release work.', sourceIds: ['history-pinecone-07'], simulated: true },
    { id: 'calendar-dinner-conflict', title: 'Avery: ceramics class', start: dinnerTime(now, 19, 0), end: dinnerTime(now, 20, 0), attendees: ['avery@example.test'], location: 'Union Square Arts Studio', description: 'Existing personal commitment. Avery needs fifteen minutes to walk from the studio to the restaurant.', sourceIds: [], simulated: true },
    { id: 'calendar-leadership', title: 'Pinecone launch review', start: dinnerTime(now, 14, 0), end: dinnerTime(now, 14, 30), attendees: ['nora@example.test', 'mina@example.test', 'owen@example.test'], location: 'Board room / demo video call', description: 'Review PIN launch metrics, open migrations, and verified checkout QA. Meeting already exists; prepare its brief.', sourceIds: [], simulated: true },
    { id: 'calendar-beacon', title: 'Beacon Grid facilities review', start: dinnerTime(now, 11, 30), end: dinnerTime(now, 12, 0), attendees: ['amir@example.test', 'sofia@example.test', 'chen@example.test'], location: 'Beacon Tower conference room', description: 'Review BG meter coverage, spending, and delayed feeds. Prepare a brief for this existing meeting.', sourceIds: [], simulated: true },
    { id: 'calendar-lumen', title: 'Lumen Museum visitor services briefing', start: dinnerTime(now, 15, 0), end: dinnerTime(now, 15, 30), attendees: ['hazel@example.test', 'finn@example.test', 'ada@example.test'], location: 'Lumen Museum Learning Studio', description: 'Review LUM bookings, access tours, and volunteer coverage. Prepare a brief for this existing meeting.', sourceIds: [], simulated: true }];
}

type EventInput = { id: string; label: string; source: Source; thread: string; author: string; title: string; content: string; attachments?: SourceAttachment[] };

export function demoEvents(now: number): Array<{ id: string; label: string; item: SourceItem }> {
  const dinnerDate = dated(now);
  const zone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const museumDate = new Date(now);
  museumDate.setMonth(museumDate.getMonth() + 1, 14);
  museumDate.setHours(10, 0, 0, 0);
  const museumStart = museumDate.toISOString();
  museumDate.setHours(12, 0, 0, 0);
  const museumEnd = museumDate.toISOString();
  const events: EventInput[] = [
    { id: 'launch-request', label: 'Nora asks for the launch report', source: 'gmail', thread: 'pinecone-launch-readout', author: 'Nora Feld', title: 'PIN launch readout for leadership', content: 'Please write the Pinecone Commerce launch readout from the archived PIN evidence. Use 170 activated merchants out of 250 eligible, support tickets 31 last week and 18 this week, and the seven open migrations with their named owners. Explain the rollout decision and open risk. Save a report for me; do not send an email. This is the PIN launch readout, separate from any Harbor Health report.' },
    { id: 'launch-cross-reference', label: 'Asana adds context to the same report', source: 'asana', thread: 'task-pin-launch-441', author: 'Nora Feld', title: 'PIN launch readout: owner appendix', content: 'This is the same Pinecone launch readout I just requested by email, not another report. Include the seven PIN-M migration owners from pin-owner-register.csv in an appendix. Use the artifact from that work for our leadership meeting.' },
    { id: 'launch-thanks', label: 'A thank-you needs no work', source: 'slack', thread: 'pin-readout-discussion', author: 'Nora Feld', title: 'Thanks for picking up the readout', content: 'Thanks for picking up the PIN launch readout. The CSV links opened fine. No new ask here; I will read the finished report.', },
    { id: 'qa-before-fix', label: 'QA request arrives before the fix', source: 'linear', thread: 'issue-PIN-185', author: 'Owen Price', title: 'PIN-185: verify the PIN-184 coupon fix', content: 'Please create a focused QA task for the upcoming PIN-184 checkout fix. QA must wait for a completed patch and then test that exact patched workspace. Check $100 subtotal at 8% tax with a fixed $10 coupon gives $97.20; full-price stays $108. Do not call the original failing checkout verified. Attach the test evidence for the leadership meeting.' },
    { id: 'checkout-regression', label: 'Slack reports a reproducible checkout bug', source: 'slack', thread: 'pin-release-172638.004', author: 'Mina Park', title: 'PIN-184: fixed $10 coupon charges tax twice', content: 'Please fix PIN-184 in the local checkout fixture. This is a fixed-value $10 coupon, not a percentage coupon. Repro: checkoutTotal(100, 0.08, 10) returns $104.40 but should return $97.20. Full-price checkoutTotal(100, 0.08) must remain $108. The coupon branch adds the $7.20 tax twice. Save the patch and test output. Owen has already requested dependent QA in PIN-185.', attachments: [attachment('pin-184-repro', 'pin-184-reproduction.json', JSON.stringify({ issue: 'PIN-184', function: 'checkoutTotal', cases: [{ subtotal: 100, taxRate: 0.08, fixedCoupon: 10, observed: 104.4, expected: 97.2 }, { subtotal: 100, taxRate: 0.08, fixedCoupon: 0, observed: 108, expected: 108 }], reporter: 'Mina Park', evidence: 'Local fixture checkout.js coupon branch' }, null, 2))] },
    { id: 'checkout-community', label: 'Discord reports the same PIN-184 issue', source: 'discord', thread: 'channel-beta-msg-9001', author: 'pixelpilot', title: 'PIN-184 receipt values from beta', content: 'Mina linked me to PIN-184. Same Pinecone checkout bug: $100 cart, fixed $10 coupon, 8% tax, total $104.40 rather than $97.20. Please add this receipt evidence to the existing PIN-184 work. I am not reporting a second checkout issue.' },
    { id: 'meeting-prep', label: 'Meeting prep needs the report and verified QA', source: 'calendar', thread: 'event-pin-leadership-2026', author: 'Nora Feld', title: 'Prepare the existing Pinecone launch review', content: `The Pinecone launch review is on ${dinnerDate}, 2:00–2:30 PM in ${zone}. Please prepare a meeting brief using the completed PIN launch report and verified PIN-185 QA for the PIN-184 patch. Wait for those artifacts; do not substitute planned work for results. List decisions and unresolved risks. The meeting already exists in the calendar, so do not create another event.` },
    { id: 'dinner-vague', label: 'A dinner request is missing a time', source: 'imessage', thread: 'chat-avery-ross-personal', author: 'Avery Ross', title: 'Dinner after the workshop?', content: 'Can you put together dinner with the Pinecone workshop group sometime soon? Six of us, near Union Square, somewhere quiet with vegetarian choices. I have not picked a date or time yet. Wait for me to confirm those before making the calendar event.' },
    { id: 'support-correction', label: 'A corrected metric updates earlier work', source: 'gmail', thread: 'pinecone-launch-readout', author: 'Eli Navarro', title: 'Correction to PIN launch support count', content: 'Correction for the existing PIN launch readout: current-week support is 17, not 18. One record was a duplicate import. Last week remains 31; adoption remains 170 of 250; all seven migrations remain open. Update the existing report or create a linked revision if it has finished. The meeting brief must use the corrected report. The attached support rows are the corrected source.', attachments: [attachment('pin-support-corrected', 'pin-support-corrected.csv', `ticket_id,project,week,status,included\n${Array.from({ length: 17 }, (_, i) => `PIN-S${301 + i},PIN,current,${i < 12 ? 'closed' : 'open'},true`).join('\n')}\nPIN-S318,PIN,current,duplicate_of_PIN-S307,false\nSUMMARY,PIN,previous,total_31,true\n`)] },
    { id: 'dinner-conflict', label: 'The proposed dinner time conflicts', source: 'gmail', thread: 'pinecone-workshop-dinner-booking', author: 'Avery Ross', title: 'Pinecone workshop dinner: try 7:30', content: `Following up on my iMessage about dinner for six: could we use ${dinnerDate} at 7:30 PM in ${zone}, at Juniper Table near Union Square? Check my existing calendar before creating anything. My ceramics class ends at 8:00 PM that evening, so this proposed time may conflict. This email and the iMessage refer to the same dinner.` },
    { id: 'dinner-confirmed', label: 'Avery confirms a conflict-free dinner', source: 'imessage', thread: 'chat-avery-ross-personal', author: 'Avery Ross', title: 'Dinner confirmed for 8:15', content: `Let's use ${dinnerDate}, 8:15–9:45 PM in ${zone}, at Juniper Table, Union Square. That gives me fifteen minutes after ceramics. Please create the calendar event for the same Pinecone workshop dinner, six attendees: avery@example.test, nora@example.test, mina@example.test, owen@example.test, eli@example.test, and sam@example.test. Two vegetarian meals; quiet indoor table. This is the final confirmed time, replacing my 7:30 suggestion. Do not book the restaurant or send invitations externally.`, attachments: [attachment('pin-dinner-details', 'pinecone-dinner.json', JSON.stringify({ title: 'Pinecone workshop dinner', start: dinnerTime(now, 20, 15), end: dinnerTime(now, 21, 45), timeZone: zone, location: 'Juniper Table, Union Square', attendees: ['avery@example.test', 'nora@example.test', 'mina@example.test', 'owen@example.test', 'eli@example.test', 'sam@example.test'], partySize: 6, dietaryNotes: 'Two vegetarian meals', calendarOnly: true }, null, 2))] },
    { id: 'meeting-context', label: 'Asana references the same meeting brief', source: 'asana', thread: 'task-pin-board-prep-445', author: 'Nora Feld', title: 'PIN leadership brief: use corrected support count', content: 'For the existing Pinecone launch review preparation, use the revised launch report with 17 support tickets and the verified PIN-185 QA result. This is additional context for the calendar-triggered brief, not a new meeting or independent report. State any blocked dependency plainly.' },
    { id: 'harbor-report', label: 'A similar request creates separate Harbor work', source: 'gmail', thread: 'harbor-pilot-readout-88', author: 'Dr. Leah Moss', title: 'HBR clinic reminder pilot readout', content: 'Please create a Harbor Health pilot report from the HBR evidence: 84 reminders delivered of 120 planned, front desk questions 24 down to 11, and $21,900 spent against $36,000 approved. Include the translated-copy risk. This is a different project from Pinecone Commerce; do not attach it to the PIN launch report or use Pinecone metrics.' },
    { id: 'old-issue-closed', label: 'A resolved Linear issue is ignored', source: 'linear', thread: 'issue-PIN-172', author: 'Mina Park', title: 'PIN-172 closed: receipt footer', content: 'Automated closed-issue digest. PIN-172 receipt footer clipping was fixed and verified last week. No regression has been observed and no action is requested. This is unrelated to the active PIN-184 coupon arithmetic issue.' },
    { id: 'newsletter', label: 'A newsletter creates no task', source: 'gmail', thread: 'newsletter-product-weekly-91', author: 'Product Weekly', title: 'This week: launch reports that people read', content: 'Our latest newsletter discusses better launch reports, calendar habits, and issue triage. Read it whenever convenient. This is a general publication, not a request to prepare a report, fix a bug, or schedule a meeting.' },
    { id: 'qa-owner-context', label: 'QA receives a scope clarification', source: 'slack', thread: 'pin-qa-172640.055', author: 'Owen Price', title: 'PIN-185 scope confirmation', content: 'For the existing PIN-185 QA task, record both coupon and full-price results from the completed PIN-184 patch workspace. The current coupon is a fixed $10 amount. Keep the QA linked to that patch and the leadership brief; do not create another QA task.' },
    { id: 'library-report', label: 'Library asks for a branch summary', source: 'asana', thread: 'task-lib-branch-review-18', author: 'Marta Bell', title: 'LIB room booking summary', content: 'Please prepare the Juniper Library branch summary from LIB evidence. We have 63 online reservations out of 90, booking questions declined from 19 to 8, and West Branch still needs phone booking while its kiosk is offline. Include each branch owner from the register. Save a report for the coordinator.' },
    { id: 'beacon-review', label: 'Facilities asks for an energy review brief', source: 'calendar', thread: 'event-bg-facilities-63', author: 'Amir Khan', title: 'BG facilities review preparation', content: `Prepare a brief for the Beacon Grid facilities review on ${dinnerDate}, 11:30 AM–12:00 PM in ${zone}, at Beacon Tower conference room, with amir@example.test, sofia@example.test, and chen@example.test. Use BG project evidence. Compare 39 connected meters with 60 planned, $46,200 spent with $75,000 approved, and explain the two delayed meter feeds. Do not use Pinecone launch metrics. The meeting is already booked.` },
    { id: 'maple-update', label: 'School asks for a club capacity report', source: 'gmail', thread: 'maple-clubs-review-9', author: 'Grace Wilson', title: 'MAP club enrollment and waitlists', content: 'Please draft the Maple School club review using MAP evidence. There are 112 confirmed enrollments out of 160 places and 12 family questions versus 28 previously. Explain the robotics and ceramics capacity risk and the dated waitlist decision. Do not include individual children or promise new places.' },
    { id: 'northstar-withdrawn', label: 'A withdrawn design request is ignored', source: 'slack', thread: 'ns-print-summary-29', author: 'Theo Grant', title: 'No need for the extra print summary', content: 'I was going to ask for a Northstar print proof summary, but Freya already wrote it and legal has the file. Please do not create another. This message withdraws that request.' },
    { id: 'orchard-report', label: 'The cooperative asks for a packing readout', source: 'asana', thread: 'task-orc-packing-51', author: 'Rosa Silva', title: 'ORC weekly box readiness', content: 'Prepare a produce-box readiness report for Orchard Cooperative from ORC evidence: 156 confirmed boxes of 200 capacity, delivery questions 35 down to 15, and the tomato supply risk. Include the seven grower owners and the approved substitute policy. This report belongs to ORC.' },
    { id: 'metro-question', label: 'An unanswered maintenance request needs work', source: 'discord', thread: 'metro-maintenance-forum-772', author: 'Dante Brooks', title: 'MET weekend station priorities', content: 'Could you write a maintenance planning brief using the Metro Mobility evidence? We need to prioritize the stations with morning outages and account for the canal depot battery shortage. Use the 52 healthy stations of 75, 13 maintenance tickets, and named station owners. Save a document; do not dispatch repair crews.' },
    { id: 'lumen-meeting', label: 'Museum visitor services needs a brief', source: 'calendar', thread: 'event-lum-visitor-review-22', author: 'Hazel Wright', title: 'LUM visitor services briefing', content: `Please prepare the existing Lumen Museum visitor services meeting on ${dinnerDate}, 3:00–3:30 PM in ${zone}, at Lumen Museum Learning Studio, with hazel@example.test, finn@example.test, and ada@example.test. Use LUM evidence for 91 member bookings of 140 slots, seven visitor questions, and volunteer coverage for Saturday access tours. Include the decision to retain step-free slots. No new calendar invitation is needed.` },
    { id: 'cedar-report', label: 'Kitchen asks for meal collection planning', source: 'gmail', thread: 'cedar-meal-review-19', author: 'Olivia Hart', title: 'CDR collection plan for volunteers', content: 'Please write a Cedar Kitchen volunteer planning report using the CDR archive. Include 128 reserved meals of 180 capacity, pickup questions 32 down to 14, and the oven inspection contingency. Keep allergy details out of the public-facing text. Save the report locally.' },
    { id: 'library-followup', label: 'Library adds evidence to its own report', source: 'slack', thread: 'lib-room-coordinators-991', author: 'Marta Bell', title: 'LIB summary: West Branch wording', content: 'For the Juniper Library room booking summary I requested in Asana, please say that phone reservations remain available at West Branch. The kiosk outage does not mean the branch is closed. Add this clarification to the same LIB report.' },
    { id: 'personal-date-vague', label: 'A separate personal plan needs details', source: 'imessage', thread: 'chat-dad-personal', author: 'Dad', title: 'Museum visit sometime next month', content: 'Could you help put a museum visit on the calendar sometime next month? I do not know which weekend or which museum yet. Please wait for those details. This is a family outing, unrelated to Avery and the Pinecone workshop dinner.' },
    { id: 'personal-date-confirmed', label: 'Dad confirms the family museum visit', source: 'imessage', thread: 'chat-dad-personal', author: 'Dad', title: 'Museum visit confirmed', content: `For the museum visit I asked about, please add a two-hour family outing at Lumen Museum on ${new Date(museumStart).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}, 10:00 AM–12:00 PM in ${zone}. Attendees are dad@example.test and you@example.test. This confirms the date and museum for that same plan. Create only the local calendar event; do not book tickets or send invitations externally. This is separate from the LUM visitor services briefing and the Pinecone dinner.`, attachments: [attachment('family-museum-details', 'family-museum-visit.json', JSON.stringify({ title: 'Family museum visit', start: museumStart, end: museumEnd, timeZone: zone, location: 'Lumen Museum', attendees: ['dad@example.test', 'you@example.test'], calendarOnly: true }, null, 2))] },
    { id: 'harbor-acknowledgment', label: 'Harbor confirms receipt without a new ask', source: 'discord', thread: 'harbor-coordinator-forum-82', author: 'Dr. Leah Moss', title: 'HBR evidence files received', content: 'The Harbor Health evidence files opened correctly. Thanks, Tessa. No correction or extra request from me; the pilot report request in email already covers what I need.' },
    { id: 'beacon-correction', label: 'Facilities corrects its own project count', source: 'linear', thread: 'issue-BG-317', author: 'Sofia Reed', title: 'BG review correction: connected meters now 40', content: 'For the existing Beacon Grid facilities review brief, one additional meter connected after the export. Use 40 connected meters of 60 planned. Spending and the delayed-feed risk are unchanged. Update that BG brief or make a linked revision if it is complete. Do not change Pinecone adoption numbers.', attachments: [attachment('bg-meter-correction', 'bg-meter-correction.md', '# Beacon Grid correction\n\nSofia Reed verified meter BG-M40 at Park Offices after the weekly export. Connected meters are now 40 of 60, replacing 39 of 60. The approved budget remains $75,000 and spending remains $46,200. The Canal House and Station Annex feeds still arrive a day late. This correction applies only to the BG facilities review.\n')] },
    { id: 'calendar-no-change', label: 'Calendar acceptance creates no duplicate event', source: 'calendar', thread: 'event-pin-leadership-2026', author: 'Mina Park', title: 'Accepted: Pinecone launch review', content: 'Mina accepted the existing Pinecone launch review invitation. The start, end, attendees, and location are unchanged. This is only an RSVP notification; no new event or separate prep task is requested.' },
    { id: 'community-social', label: 'A social comment needs no agent', source: 'discord', thread: 'office-lounge-478', author: 'nightowl', title: 'Those office plants', content: 'The tiny office plants look great. I would happily work next to that window. Just chatting, no task for anyone.' },
  ];
  events.push(...readArrivalSequence('gmail'), ...readArrivalSequence('slack'));
  const result = events.map((event, index) => ({ id: `arrival-${event.id}`, label: event.label, item: {
    id: `source-${event.id}`, source: event.source, externalId: `${event.source}-delivery-${event.id}`,
    threadId: `${event.source}:${event.thread}`, author: event.author, title: event.title, content: event.content,
    timestamp: now + index * 90_000,
    ...(event.source === 'slack' || event.source === 'discord' ? { channel: event.id.startsWith('checkout') || event.id.startsWith('qa-') ? '#pinecone-release' : '#project-updates' } : {}),
    ...(event.attachments ? { attachments: event.attachments } : {}),
  } }));
  // Provider redelivery repeats the external identity, while the transport event has its own ID.
  result.splice(6, 0, { ...result[4], id: 'arrival-checkout-provider-redelivery', label: 'Slack redelivers the same event', item: { ...result[4].item, timestamp: now + 6 * 90_000 } });
  return result;
}
