import type {
  ActionProposal,
  ActivityEvent,
  Artifact,
  Connection,
  Dashboard,
  Employee,
  InboxItem,
  Listing,
  Project,
  ProviderConfig,
  ProviderReadiness,
  RegistryTool,
  Task,
} from '@/lib/contracts';
import type { EditorDraft } from '@/components/admin/draft-issues';
import { asId } from '@/lib/ui-api';

/**
 * A full workspace, written down. It exists so the interface can be photographed and reviewed at
 * every viewport without a Convex deployment, a Clerk instance, or a real employee doing work. Every
 * status, correction kind, and sharing state the interface can render appears at least once.
 */

const hour = 3_600_000;
/** A fixed clock so screenshots taken on different days are comparable. */
const now = Date.UTC(2026, 2, 17, 14, 30);
const ago = (hours: number) => now - hours * hour;

const employees: Employee[] = [
  {
    id: 'emp_ada',
    versionId: 'ver_ada',
    name: 'Ada',
    role: 'Operations analyst',
    color: '#6864d9',
    model: 'gpt-6-astra',
    status: 'ready',
    missingCapabilities: [],
    persona: {
      voice: 'Writes in short declaratives and says what she is unsure about before anything else.',
      traits: ['precise', 'fast', 'dry humour'],
      catchphrase: 'Numbers first, opinions after.',
    },
  },
  {
    id: 'emp_bruno',
    versionId: 'ver_bruno',
    name: 'Bruno',
    role: 'Release writer',
    color: '#c2683a',
    model: 'gpt-5.6-terra',
    status: 'ready',
    missingCapabilities: [],
    persona: {
      voice: 'Warm and plain-spoken. Explains the reasoning before the recommendation.',
      traits: ['careful', 'thorough'],
    },
  },
  {
    id: 'emp_mina',
    versionId: 'ver_mina',
    name: 'Mina',
    role: 'Support triage',
    color: '#3a8f7a',
    model: 'gpt-5.6-luna',
    status: 'blocked',
    missingCapabilities: ['slack'],
    persona: {
      voice: 'Asks one clarifying question, then works without further prompting.',
      traits: ['cautious', 'literal', 'patient'],
      catchphrase: 'One question, then I am out of your way.',
    },
  },
];

const connections: Connection[] = [
  {
    id: 'conn_linear',
    provider: 'linear',
    name: 'Linear',
    account: 'acme',
    serverUrl: 'https://mcp.linear.app/mcp',
    status: 'connected',
    ownerSubject: 'user_dana',
    ownerName: 'Dana Okoye',
    isOwner: true,
    visibility: 'workspace',
    visibleToSubjects: [],
    tools: ['get_issue', 'list_issues', 'update_issue', 'create_comment'],
    allowedTools: ['get_issue', 'list_issues', 'update_issue'],
    resourceScope: 'ENG,DESIGN',
    inboxResources: ['a1b2c3d4-eng'],
    lastCheckedAt: ago(1),
    inboxMode: 'push',
  },
  {
    id: 'conn_github',
    provider: 'github',
    name: 'GitHub',
    account: 'acme-platform',
    serverUrl: 'https://api.githubcopilot.com/mcp/',
    status: 'connected',
    ownerSubject: 'user_ivan',
    ownerName: 'Ivan Petrov',
    isOwner: false,
    visibility: 'members',
    visibleToSubjects: ['user_dana', 'user_ivan'],
    tools: ['get_me', 'list_pull_requests', 'create_issue'],
    allowedTools: ['get_me', 'list_pull_requests'],
    resourceScope: 'acme/platform',
    inboxResources: ['acme/platform'],
    lastCheckedAt: ago(3),
    inboxMode: 'push',
  },
  {
    id: 'conn_slack',
    provider: 'slack',
    name: 'Slack',
    account: 'acme.slack.com',
    serverUrl: 'https://mcp.slack.com/mcp',
    status: 'degraded',
    ownerSubject: 'user_dana',
    ownerName: 'Dana Okoye',
    isOwner: true,
    visibility: 'private',
    visibleToSubjects: [],
    tools: ['list_channels', 'post_message'],
    allowedTools: ['list_channels'],
    resourceScope: '',
    inboxResources: [],
    lastCheckedAt: ago(26),
    inboxMode: 'on-demand',
    error: 'The workspace token was refused on the last check. Reconnect to restore delivery.',
  },
];

const projects: Project[] = [
  {
    id: 'proj_launch',
    name: 'Spring launch',
    brief: 'Ship the March release: changelog, migration notes, and the customer announcement.',
    employeeIds: ['emp_ada', 'emp_bruno'],
    createdAt: ago(96),
    updatedAt: ago(2),
    openHandoffs: 2,
  },
  {
    id: 'proj_support',
    name: 'Support backlog',
    brief: 'Triage the open support queue and escalate anything touching billing.',
    employeeIds: ['emp_mina', 'emp_ada'],
    createdAt: ago(240),
    updatedAt: ago(9),
    openHandoffs: 1,
  },
];

const tasks: Task[] = [
  {
    id: 'task_queued',
    employeeId: 'emp_ada',
    employeeName: 'Ada',
    createdBy: 'user_dana',
    createdByName: 'Dana Okoye',
    isOwner: true,
    visibility: 'private',
    title: 'Summarise the open launch blockers',
    prompt: 'List every Linear issue blocking the March release and who owns it.',
    status: 'queued',
    createdAt: ago(0.2),
    updatedAt: ago(0.2),
    model: 'gpt-6-astra',
  },
  {
    id: 'task_running',
    projectId: 'proj_launch',
    projectContext: { name: 'Spring launch', brief: 'Ship the March release.' },
    employeeId: 'emp_ada',
    employeeName: 'Ada',
    createdBy: 'user_dana',
    createdByName: 'Dana Okoye',
    isOwner: true,
    visibility: 'workspace',
    title: 'Draft the migration notes',
    prompt: 'Draft migration notes for the schema change in acme/platform#4120.',
    status: 'running',
    createdAt: ago(1.5),
    updatedAt: ago(0.1),
    sessionId: 'sess_running',
    model: 'gpt-6-astra',
    usage: { input: 48_200, cached: 21_000, output: 6_400 },
    lastMessage: {
      text: 'Reading the pull request diff to work out which columns changed and whether the change is reversible.',
      createdAt: ago(0.1),
      phase: 'reading',
    },
  },
  {
    id: 'task_awaiting',
    projectId: 'proj_launch',
    projectContext: { name: 'Spring launch', brief: 'Ship the March release.' },
    employeeId: 'emp_bruno',
    employeeName: 'Bruno',
    createdBy: 'user_ivan',
    createdByName: 'Ivan Petrov',
    isOwner: false,
    visibility: 'workspace',
    title: 'Update the changelog issue',
    prompt: 'Add the finished changelog to ENG-4120 and mark it ready for review.',
    status: 'awaiting_approval',
    createdAt: ago(4),
    updatedAt: ago(0.6),
    sessionId: 'sess_awaiting',
    model: 'gpt-5.6-terra',
    usage: { input: 31_000, cached: 8_000, output: 3_100 },
    lastMessage: {
      text: 'The changelog is ready. I need approval before writing it back to Linear.',
      createdAt: ago(0.6),
      phase: 'waiting',
    },
  },
  {
    id: 'task_completed',
    projectId: 'proj_launch',
    projectContext: { name: 'Spring launch', brief: 'Ship the March release.' },
    sourceTaskId: 'task_running',
    employeeId: 'emp_bruno',
    employeeName: 'Bruno',
    createdBy: 'user_dana',
    createdByName: 'Dana Okoye',
    isOwner: true,
    visibility: 'workspace',
    title: 'Write the customer announcement',
    prompt: 'Write the announcement for the March release, 200 words, no marketing language.',
    status: 'completed',
    createdAt: ago(28),
    updatedAt: ago(24),
    sessionId: 'sess_completed',
    model: 'gpt-5.6-terra',
    usage: { input: 62_400, cached: 40_100, output: 9_800 },
    lastMessage: { text: 'Announcement written and saved to outputs/announcement.md.', createdAt: ago(24) },
  },
  {
    id: 'task_failed',
    employeeId: 'emp_mina',
    employeeName: 'Mina',
    createdBy: 'user_dana',
    createdByName: 'Dana Okoye',
    isOwner: true,
    visibility: 'private',
    title: 'Triage the billing escalations',
    prompt: 'Read the #billing channel and list every unresolved escalation.',
    status: 'failed',
    createdAt: ago(30),
    updatedAt: ago(29),
    model: 'gpt-5.6-luna',
    error: 'Slack refused the request. Its connection needs attention before this can run again.',
  },
  {
    id: 'task_cancelled',
    employeeId: 'emp_ada',
    employeeName: 'Ada',
    createdBy: 'user_dana',
    createdByName: 'Dana Okoye',
    isOwner: true,
    visibility: 'private',
    title: 'Audit last quarter spend',
    prompt: 'Compare last quarter token spend against the cap by employee.',
    status: 'cancelled',
    createdAt: ago(52),
    updatedAt: ago(51),
    model: 'gpt-5.6-sol',
  },
  {
    id: 'task_uncertain',
    projectId: 'proj_support',
    projectContext: { name: 'Support backlog', brief: 'Triage the open support queue.' },
    employeeId: 'emp_mina',
    employeeName: 'Mina',
    createdBy: 'user_ivan',
    createdByName: 'Ivan Petrov',
    isOwner: false,
    visibility: 'workspace',
    title: 'Close the duplicate support issues',
    prompt: 'Close every duplicate in the support queue and link it to the original.',
    status: 'uncertain',
    createdAt: ago(9),
    updatedAt: ago(8),
    sessionId: 'sess_uncertain',
    model: 'gpt-5.6-luna',
    error: 'A write was sent but no result came back. Check Linear before retrying.',
    lastMessage: {
      text: 'I sent the close request and never saw a result. Stopping so nothing is done twice.',
      createdAt: ago(8),
      phase: 'stopped',
    },
  },
];

const proposals: ActionProposal[] = [
  {
    id: 'prop_pending',
    taskId: 'task_awaiting',
    connectionId: 'conn_linear',
    employeeName: 'Bruno',
    provider: 'linear',
    tool: 'update_issue',
    arguments: JSON.stringify({ id: 'ENG-4120', description: 'Changelog for the March release.' }, null, 2),
    summary: 'Update ENG-4120 with the finished changelog',
    status: 'pending',
    correction: 'supported',
    correctionReason: 'The issue can be restored from its previous description.',
    beforeState: JSON.stringify({ description: 'TODO: changelog', version: 7 }, null, 2),
    createdAt: ago(0.6),
    canDecide: true,
  },
  {
    id: 'prop_approved',
    taskId: 'task_awaiting',
    connectionId: 'conn_linear',
    employeeName: 'Bruno',
    provider: 'linear',
    tool: 'create_comment',
    arguments: JSON.stringify({ issueId: 'ENG-4120', body: 'Ready for review.' }, null, 2),
    summary: 'Comment on ENG-4120 that the changelog is ready',
    status: 'approved',
    correction: 'partial',
    correctionReason: 'A comment can be edited but not withdrawn.',
    createdAt: ago(0.7),
    approvedBy: 'user_dana',
    approvedByName: 'Dana Okoye',
    approvedAt: ago(0.65),
    canDecide: true,
  },
  {
    id: 'prop_executing',
    taskId: 'task_running',
    connectionId: 'conn_github',
    employeeName: 'Ada',
    provider: 'github',
    tool: 'create_issue',
    arguments: JSON.stringify({ repo: 'acme/platform', title: 'Document the column rename' }, null, 2),
    summary: 'Open an issue for the undocumented column rename',
    status: 'executing',
    correction: 'manual',
    correctionReason: 'Issues cannot be deleted; closing one needs a person.',
    createdAt: ago(0.4),
    approvedBy: 'user_ivan',
    approvedByName: 'Ivan Petrov',
    approvedAt: ago(0.35),
    canDecide: false,
  },
  {
    id: 'prop_succeeded',
    taskId: 'task_completed',
    connectionId: 'conn_linear',
    employeeName: 'Bruno',
    provider: 'linear',
    tool: 'update_issue',
    arguments: JSON.stringify({ id: 'ENG-4088', state: 'Done' }, null, 2),
    summary: 'Mark ENG-4088 done',
    status: 'succeeded',
    correction: 'supported',
    correctionReason: 'The previous state can be restored.',
    beforeState: JSON.stringify({ state: 'In Progress', version: 3 }, null, 2),
    afterState: JSON.stringify({ state: 'Done', version: 4 }, null, 2),
    createdAt: ago(25),
    approvedBy: 'user_dana',
    approvedByName: 'Dana Okoye',
    approvedAt: ago(24.8),
    result: 'ENG-4088 moved to Done.',
    canDecide: true,
  },
  {
    id: 'prop_rejected',
    taskId: 'task_completed',
    connectionId: 'conn_slack',
    employeeName: 'Bruno',
    provider: 'slack',
    tool: 'post_message',
    arguments: JSON.stringify({ channel: '#general', text: 'The release is out.' }, null, 2),
    summary: 'Announce the release in #general',
    status: 'rejected',
    correction: 'irreversible',
    correctionReason: 'A posted message cannot be unsent.',
    createdAt: ago(26),
    approvedBy: 'user_dana',
    approvedByName: 'Dana Okoye',
    approvedAt: ago(25.9),
    result: 'Rejected. The announcement goes out by email instead.',
    canDecide: true,
  },
  {
    id: 'prop_failed',
    taskId: 'task_failed',
    connectionId: 'conn_slack',
    employeeName: 'Mina',
    provider: 'slack',
    tool: 'list_channels',
    arguments: JSON.stringify({ limit: 200 }, null, 2),
    summary: 'Read the channel list to find the billing channel',
    status: 'failed',
    correction: 'unknown',
    correctionReason: 'The provider gave no result, so the outcome is unknown.',
    createdAt: ago(29.5),
    result: 'Slack refused the request: invalid_auth.',
    canDecide: false,
  },
  {
    id: 'prop_uncertain',
    taskId: 'task_uncertain',
    connectionId: 'conn_linear',
    employeeName: 'Mina',
    provider: 'linear',
    tool: 'update_issue',
    arguments: JSON.stringify({ id: 'SUP-233', state: 'Duplicate' }, null, 2),
    summary: 'Close SUP-233 as a duplicate',
    status: 'uncertain',
    correction: 'unknown',
    correctionReason: 'No result came back, so it is unclear whether the write landed.',
    createdAt: ago(8.2),
    approvedBy: 'user_ivan',
    approvedByName: 'Ivan Petrov',
    approvedAt: ago(8.1),
    canDecide: false,
  },
  {
    id: 'prop_corrected',
    taskId: 'task_completed',
    connectionId: 'conn_linear',
    employeeName: 'Bruno',
    provider: 'linear',
    tool: 'update_issue',
    arguments: JSON.stringify({ id: 'ENG-4001', title: 'Renamed by mistake' }, null, 2),
    summary: 'Rename ENG-4001',
    status: 'corrected',
    correction: 'supported',
    correctionReason: 'The original title was restored.',
    beforeState: JSON.stringify({ title: 'Original title', version: 11 }, null, 2),
    afterState: JSON.stringify({ title: 'Renamed by mistake', version: 12 }, null, 2),
    createdAt: ago(40),
    approvedBy: 'user_dana',
    approvedByName: 'Dana Okoye',
    approvedAt: ago(39.9),
    result: 'Corrected by a follow-up action.',
    originalActionId: 'prop_succeeded',
    canDecide: true,
  },
];

const events: ActivityEvent[] = [
  {
    id: 'evt_1',
    sequence: 41,
    taskId: 'task_running',
    type: 'tool_call',
    text: 'Ada read acme/platform#4120 on GitHub.',
    createdAt: ago(0.3),
    employeeName: 'Ada',
  },
  {
    id: 'evt_2',
    sequence: 40,
    taskId: 'task_awaiting',
    type: 'proposal',
    text: 'Bruno proposed updating ENG-4120 and is waiting for approval.',
    createdAt: ago(0.6),
    employeeName: 'Bruno',
  },
  {
    id: 'evt_3',
    sequence: 38,
    taskId: 'task_uncertain',
    type: 'error',
    text: 'Mina stopped after a write with no result.',
    createdAt: ago(8),
    employeeName: 'Mina',
    gap: true,
  },
  {
    id: 'evt_4',
    sequence: 12,
    taskId: 'task_completed',
    type: 'artifact',
    text: 'Bruno saved announcement.md.',
    createdAt: ago(24),
    employeeName: 'Bruno',
  },
];

const inbox: InboxItem[] = [
  {
    id: 'inbox_unread',
    provider: 'linear',
    title: 'ENG-4131 Migration script fails on empty tables',
    preview: 'Reported by a customer on the staging deploy. Reproduces every time on a fresh database.',
    sourceUrl: 'https://linear.app/acme/issue/ENG-4131',
    createdAt: ago(0.4),
    status: 'unread',
  },
  {
    id: 'inbox_read',
    provider: 'github',
    title: 'acme/platform#4127 Revert the column rename',
    preview: 'Opened by ivan. Reverts the rename until the migration notes land.',
    sourceUrl: 'https://github.com/acme/platform/pull/4127',
    createdAt: ago(5),
    status: 'read',
  },
  {
    id: 'inbox_assigned',
    provider: 'linear',
    title: 'SUP-233 Duplicate of SUP-190',
    preview: 'Same report filed twice by the same customer.',
    createdAt: ago(9.5),
    status: 'assigned',
    taskId: 'task_uncertain',
  },
];

const artifacts: Artifact[] = [
  {
    id: 'art_announcement',
    taskId: 'task_completed',
    name: 'announcement.md',
    mediaType: 'text/markdown',
    size: 4_812,
    createdAt: ago(24),
  },
  {
    id: 'art_migration',
    taskId: 'task_running',
    name: 'migration-notes.md',
    mediaType: 'text/markdown',
    size: 11_204,
    createdAt: ago(0.2),
  },
  {
    id: 'art_spend',
    taskId: 'task_cancelled',
    name: 'spend-q4.csv',
    mediaType: 'text/csv',
    size: 92_318,
    createdAt: ago(51),
  },
];

export const dashboard: Dashboard = {
  workspace: {
    id: 'ws_acme',
    name: 'Acme',
    role: 'owner',
    monthlyTokenCap: 5_000_000,
    usage: {
      period: '2026-03',
      byModel: [
        { model: 'gpt-6-astra', input: 620_000, cached: 410_000, output: 74_000, tasks: 12 },
        { model: 'gpt-5.6-terra', input: 310_000, cached: 120_000, output: 41_000, tasks: 8 },
        { model: 'gpt-5.6-luna', input: 88_000, cached: 12_000, output: 9_400, tasks: 3 },
      ],
    },
  },
  viewer: { subject: 'user_dana', name: 'Dana Okoye' },
  isPlatformAdmin: true,
  employees,
  connections,
  projects,
  tasks,
  events,
  proposals,
  inbox,
  artifacts,
};

export const listings: Listing[] = [
  {
    id: 'ver_ada',
    versionId: 'ver_ada',
    name: 'Ada',
    role: 'Operations analyst',
    description: 'Reads your issue tracker and repositories and answers questions about the work.',
    category: 'Operations',
    strengths: ['Traces a change across tools', 'Says what it cannot verify'],
    limitations: ['Never posts publicly', 'Will not close issues without approval'],
    capabilities: [
      { provider: 'linear', tools: ['get_issue', 'list_issues'], optional: false },
      { provider: 'github', tools: ['list_pull_requests'], optional: true },
    ],
    model: 'gpt-6-astra',
    color: '#6864d9',
    media: [],
    persona: {
      voice: 'Writes in short declaratives and says what she is unsure about first.',
      traits: ['precise', 'fast'],
    },
    publishedAt: ago(400),
  },
  {
    id: 'ver_bruno',
    versionId: 'ver_bruno',
    name: 'Bruno',
    role: 'Release writer',
    description: 'Turns a set of merged changes into notes a customer can read.',
    category: 'Writing',
    strengths: ['Plain language', 'Keeps the changelog consistent'],
    limitations: ['Needs the diff to be readable'],
    capabilities: [{ provider: 'github', tools: ['list_pull_requests'], optional: false }],
    model: 'gpt-5.6-terra',
    color: '#c2683a',
    media: [],
    publishedAt: ago(300),
  },
  {
    id: 'ver_mina',
    versionId: 'ver_mina',
    name: 'Mina',
    role: 'Support triage',
    description: 'Sorts the support queue and escalates what a person has to see.',
    category: 'Support',
    strengths: ['Finds duplicates', 'Asks before guessing'],
    limitations: ['Does not answer customers directly'],
    capabilities: [
      { provider: 'linear', tools: ['list_issues', 'update_issue'], optional: false },
      { provider: 'slack', tools: ['list_channels'], optional: false },
    ],
    model: 'gpt-5.6-luna',
    color: '#3a8f7a',
    media: [],
    persona: { voice: 'Asks one clarifying question, then works.', traits: ['cautious', 'patient'] },
    publishedAt: ago(120),
  },
];

export const drafts: EditorDraft[] = [
  {
    id: 'draft_scribe',
    draftId: asId('draft_scribe'),
    persona: undefined,
    name: 'Scribe',
    role: 'Meeting notes',
    description: 'Turns a transcript into decisions and owners.',
    category: 'Writing',
    color: '#8a5fbd',
    model: 'gpt-5.6-terra',
    instructions: 'Summarise decisions, owners, and dates. Never invent an owner.',
    strengths: ['Finds decisions'],
    limitations: ['Needs a transcript'],
    capabilities: [{ provider: 'google-workspace', tools: ['docs_get'], optional: false }],
    media: [],
    skills: [],
    updatedAt: ago(6),
  },
];

export const registryTools: RegistryTool[] = [
  {
    provider: 'linear',
    name: 'get_issue',
    description: 'Read one issue by identifier.',
    mode: 'read',
    resourceArgument: 'teamId',
    annotations: { readOnlyHint: true },
    updatedAt: ago(500),
    updatedBy: 'user_dana',
  },
  {
    provider: 'linear',
    name: 'update_issue',
    description: 'Change fields on one issue.',
    mode: 'write',
    resourceArgument: 'teamId',
    correction: {
      readTool: 'get_issue',
      idArgument: 'id',
      versionField: 'version',
      expectedVersionArgument: 'expectedVersion',
      fields: ['title', 'description', 'state'],
    },
    updatedAt: ago(500),
    updatedBy: 'user_dana',
  },
  {
    provider: 'github',
    name: 'list_pull_requests',
    description: 'List pull requests on a repository.',
    mode: 'read',
    resourceArgument: 'repo',
    annotations: { readOnlyHint: true },
    updatedAt: ago(480),
    updatedBy: 'user_dana',
  },
  {
    provider: 'slack',
    name: 'post_message',
    description: 'Post a message to a channel.',
    mode: 'blocked',
    annotations: { destructiveHint: false },
    updatedAt: ago(200),
    updatedBy: 'user_dana',
  },
];

export const providerConfigs: ProviderConfig[] = [
  {
    provider: 'linear',
    enabledUrls: ['https://mcp.linear.app/mcp'],
    oauthClients: [{ clientId: 'linear-client', hasClientSecret: true, scopes: 'read,write' }],
    hasInboxSecret: true,
    updatedAt: ago(500),
    updatedBy: 'user_dana',
  },
  {
    provider: 'github',
    enabledUrls: ['https://api.githubcopilot.com/mcp/'],
    oauthClients: [
      { serverUrl: 'https://api.githubcopilot.com/mcp/', clientId: 'gh-client', hasClientSecret: true },
    ],
    hasInboxSecret: false,
    updatedAt: ago(480),
    updatedBy: 'user_dana',
  },
  { provider: 'slack', enabledUrls: [], oauthClients: [], hasInboxSecret: false },
  { provider: 'google-workspace', enabledUrls: [], oauthClients: [], hasInboxSecret: false },
  { provider: 'canva', enabledUrls: [], oauthClients: [], hasInboxSecret: false },
];

export const readiness: ProviderReadiness[] = [
  {
    provider: 'linear',
    enabledUrls: ['https://mcp.linear.app/mcp'],
    oauthUrls: ['https://mcp.linear.app/mcp'],
    reviewedTools: 2,
    inboxConfigured: true,
  },
  {
    provider: 'github',
    enabledUrls: ['https://api.githubcopilot.com/mcp/'],
    oauthUrls: ['https://api.githubcopilot.com/mcp/'],
    reviewedTools: 1,
    inboxConfigured: false,
  },
  { provider: 'slack', enabledUrls: [], oauthUrls: [], reviewedTools: 0, inboxConfigured: false },
  {
    provider: 'google-workspace',
    enabledUrls: [],
    oauthUrls: [],
    reviewedTools: 0,
    inboxConfigured: false,
  },
  { provider: 'canva', enabledUrls: [], oauthUrls: [], reviewedTools: 0, inboxConfigured: false },
];

export type QaFixture = {
  dashboard: Dashboard;
  listings: Listing[];
  drafts: EditorDraft[];
  registryTools: RegistryTool[];
  providerConfigs: ProviderConfig[];
  readiness: ProviderReadiness[];
};

export const qaFixture: QaFixture = {
  dashboard,
  listings,
  drafts,
  registryTools,
  providerConfigs,
  readiness,
};
