export type OfficeStation =
  | 'desk'
  | 'archive'
  | 'library'
  | 'dispatch'
  | 'workbench'
  | 'research'
  | 'analysis'
  | 'connections'
  | 'review'
  | 'recorder';
export interface OfficeToolAnalogy {
  id: string;
  label: string;
  mechanism: string;
  object: string;
  action: string;
  evidence: string;
  station: OfficeStation;
  toolNames: readonly string[];
  availability: 'core' | 'optional';
}
const entry = (
  id: string,
  label: string,
  mechanism: string,
  object: string,
  action: string,
  evidence: string,
  station: OfficeStation,
  toolNames: readonly string[] = [],
  availability: OfficeToolAnalogy['availability'] = 'core',
): OfficeToolAnalogy => ({
  id,
  label,
  mechanism,
  object,
  action,
  evidence,
  station,
  toolNames,
  availability,
});

/** One vocabulary for the office, execution receipts, configuration, and replay. */
export const OFFICE_TOOL_ATLAS: readonly OfficeToolAnalogy[] = [
  entry(
    'session',
    'An employee at work',
    'Persistent Astra response chain',
    'Personal desk and assignment folder',
    'Opens the assigned brief and continues the same work folder across turns.',
    'Session ID, run ID, response ID, and recorded lifecycle state.',
    'desk',
  ),
  entry(
    'persona',
    'Role charter',
    'Persona and system instructions',
    'Signed role charter beside the nameplate',
    'Uses a chosen purpose, values, voice, decision style, and collaboration style.',
    'Saved configuration revision and the run’s frozen configuration.',
    'desk',
  ),
  entry(
    'reasoning',
    'Focus time',
    'Configured model reasoning effort',
    'Focus lamp',
    'Shows an observed active run; deeper effort is a setting on the lamp.',
    'Configured effort and provider run status. No invented thoughts.',
    'desk',
  ),
  entry(
    'working-memory',
    'Scratchpad',
    'Working memory',
    'Scratchpad in the employee’s drawer',
    'Keeps typed temporary working notes when memory is permitted.',
    'Working memory entry, owner, scope, provenance, and expiry.',
    'archive',
  ),
  entry(
    'episodic-memory',
    'Work journal',
    'Episodic memory',
    'Dated journal',
    'Files a useful experience for later reference.',
    'Episodic memory entry with source session and retention.',
    'archive',
  ),
  entry(
    'semantic-memory',
    'Fact cabinet',
    'Semantic memory',
    'Labeled fact drawers',
    'Files a fact card under its permitted scope.',
    'Semantic memory entry and the successful tool receipt.',
    'archive',
  ),
  entry(
    'procedural-memory',
    'Playbook shelf',
    'Procedural memory',
    'Procedures binder',
    'Keeps a reusable method for future assignments.',
    'Procedural memory entry and provenance.',
    'archive',
  ),
  entry(
    'preference-memory',
    'Working agreement',
    'Preference memory',
    'Preference card in the employee’s folder',
    'Remembers how you want work prepared.',
    'User-edited or approved preference entry.',
    'archive',
  ),
  entry(
    'memory-save',
    'File a memory',
    'memory_remember and durable local persistence',
    'Filing cabinet',
    'Places a new memory card in the configured drawer.',
    'Committed memory record and memory.saved event; proposals stay separate.',
    'archive',
    ['memory_remember'],
  ),
  entry(
    'memory-proposal',
    'In tray for review',
    'Proposed memory',
    'Unfiled card in an approval tray',
    'Offers a memory for your approval before it can be recalled.',
    'memory.proposed event and inactive proposed status.',
    'archive',
  ),
  entry(
    'memory-search',
    'Look through the index',
    'memory_search',
    'Card index and cabinet drawer',
    'Finds permitted active memories relevant to the task.',
    'Search tool receipt; expired and disallowed memories are excluded.',
    'archive',
    ['memory_search'],
  ),
  entry(
    'memory-forget',
    'Remove a memory',
    'memory_forget and retention eviction',
    'Shredder beside the cabinet',
    'Removes the active local memory card and records the removal.',
    'memory.forgotten event. Earlier conversations and exports are separate records.',
    'archive',
    ['memory_forget'],
  ),
  entry(
    'memory-private',
    'Private drawer',
    'Employee memory scope',
    'Employee-labeled drawer',
    'Keeps memory available to its owner.',
    'Owner and scope checks on each retrieval.',
    'archive',
  ),
  entry(
    'memory-session',
    'Assignment folder',
    'Session memory scope',
    'Folder bound to one assignment conversation',
    'Keeps context within its recorded session.',
    'Session ownership and scope checks.',
    'archive',
  ),
  entry(
    'memory-shared',
    'Shared cabinet',
    'Workspace memory scope',
    'Shared reference cabinet',
    'Shares only memories allowed by the employee’s settings.',
    'Explicit workspace scope and permission checks.',
    'archive',
  ),
  entry(
    'memory-limits',
    'Drawer labels and expiry tabs',
    'Retention, entry limits, context limits',
    'Dated dividers and a limited reading stack',
    'Keeps only eligible records and brings a bounded selection to the desk.',
    'Retention checks and configured context/entry limits.',
    'archive',
  ),
  entry(
    'workspace-search',
    'Search the library',
    'workspace_search',
    'Library card catalogue',
    'Looks for relevant passages in selected working copies.',
    'Search receipt tied to an authorized file snapshot.',
    'library',
    ['workspace_search'],
  ),
  entry(
    'workspace-read',
    'Read a working copy',
    'workspace_read',
    'Reading desk',
    'Opens the selected document or a bounded passage.',
    'Read receipt for the exact snapshot path and range.',
    'library',
    ['workspace_read'],
  ),
  entry(
    'file-permission',
    'Visitor’s reading pass',
    'Explicit snapshot selection and cloud-sharing consent',
    'Document checkout slip',
    'Only carries documents selected for this run to the reading desk.',
    'Selected snapshot IDs and explicit sharing choice.',
    'library',
  ),
  entry(
    'artifact-write',
    'Prepare a deliverable',
    'artifact_write',
    'Drafting bench and document printer',
    'Places a completed document in the out tray.',
    'Committed artifact ID, content, session, and tool receipt.',
    'workbench',
    ['artifact_write'],
  ),
  entry(
    'artifact-list',
    'Browse completed work',
    'artifact_list',
    'Deliverable shelf',
    'Looks through the employee’s saved documents.',
    'Owned artifact-list result.',
    'workbench',
    ['artifact_list'],
  ),
  entry(
    'artifact-read',
    'Open a deliverable',
    'artifact_read',
    'Document stand',
    'Reads a previously saved deliverable.',
    'Owned artifact-read receipt.',
    'workbench',
    ['artifact_read'],
  ),
  entry(
    'artifact-export',
    'Hand over a copy',
    'Native artifact export',
    'Document out tray',
    'Hands you a file after you choose its destination.',
    'Actual native export result; saving an artifact alone is not an export.',
    'workbench',
  ),
  entry(
    'directory',
    'Find a teammate',
    'office_list_employees',
    'Staff directory',
    'Finds teammates they are allowed to contact.',
    'Permission-filtered employee directory result.',
    'dispatch',
    ['office_list_employees'],
  ),
  entry(
    'message-send',
    'Send an envelope',
    'office_send_message',
    'Outgoing mail tray',
    'Places an addressed envelope in the internal queue.',
    'message.queued event with sender, recipient, and message ID.',
    'dispatch',
    ['office_send_message'],
  ),
  entry(
    'message-read',
    'Open the inbox',
    'office_read_inbox',
    'Personal inbox tray',
    'Opens messages actually addressed to the employee.',
    'message.delivered event; reading does not imply acknowledgment.',
    'dispatch',
    ['office_read_inbox'],
  ),
  entry(
    'message-ack',
    'Stamp received',
    'office_acknowledge_message',
    'Received stamp',
    'Stamps one message after explicitly acknowledging it.',
    'message.acknowledged event for that exact message ID.',
    'dispatch',
    ['office_acknowledge_message'],
  ),
  entry(
    'auto-wake',
    'Desk bell',
    'Configured on-message initiative',
    'Desk bell',
    'Wakes an idle employee only when automatic response is enabled.',
    'Permitted delivery followed by a real session invocation.',
    'dispatch',
    [],
    'optional',
  ),
  entry(
    'handoff-bound',
    'Routing slip',
    'Handoff depth and recipient allowlists',
    'Envelope routing slip',
    'Shows who may receive a handoff and how far the chain may continue.',
    'Checked recipient policy and recorded handoff limit.',
    'dispatch',
  ),
  entry(
    'announcement',
    'Office noticeboard',
    'Manager broadcast',
    'Noticeboard',
    'Routes your written direction to employees who accept announcements.',
    'Saved manager message and separate real session dispatches.',
    'dispatch',
  ),
  entry(
    'web',
    'Research terminal',
    'Provider web search',
    'Research terminal with a globe marker',
    'Searches external sources only when enabled.',
    'Provider web-search call result; no result is invented.',
    'research',
    ['web_search', 'web_search_call'],
    'optional',
  ),
  entry(
    'analysis',
    'Analysis bench',
    'Provider code interpreter',
    'Calculator and analysis bench',
    'Runs calculations or data analysis when enabled.',
    'Provider code-interpreter call result and returned output.',
    'analysis',
    ['code_interpreter', 'code_interpreter_call'],
    'optional',
  ),
  entry(
    'integration',
    'Service line',
    'Configured remote MCP tools',
    'Labeled service phone',
    'Uses the selected service line, respecting its approval policy.',
    'Exact remote tool name, requested arguments, approval, and provider receipt.',
    'connections',
    ['mcp', 'mcp_call', 'mcp_list_tools'],
    'optional',
  ),
  entry(
    'tool-review',
    'Decision on your desk',
    'Exact-action tool approval',
    'Manager’s review desk',
    'Brings the exact requested action to you before execution.',
    'Version-bound approval and the resulting tool receipt.',
    'review',
  ),
  entry(
    'completion-review',
    'Deliverable review',
    'Human review of completed work',
    'Review folder and approval stamp',
    'Presents the finished output for your judgment.',
    'Exact output version and recorded review decision.',
    'review',
  ),
  entry(
    'guidance-queue',
    'Next-step note',
    'Durable queued manager guidance',
    'Note clipped to the assignment folder',
    'Keeps a new instruction ready for the next turn without discarding current work.',
    'Persisted guidance ID and its later continuation.',
    'desk',
  ),
  entry(
    'budgets',
    'Work allowance',
    'Token, tool, turn, and runtime limits',
    'Desk timer and work allowance card',
    'Shows observed consumption against the limits you chose.',
    'Provider usage, local tool receipts, and enforced dispatch bounds.',
    'desk',
  ),
  entry(
    'cancel',
    'Stop card',
    'Transport abort and provider cancellation attempt',
    'Stop card on the active folder',
    'Stops local work and shows whether remote cancellation was confirmed.',
    'Cancellation state and any explicit remote uncertainty.',
    'desk',
  ),
  entry(
    'failure',
    'Help flag',
    'Tool or provider failure',
    'Raised help flag',
    'Calls attention to the actual failure with a useful next action.',
    'Failure receipt or provider error, not an inferred emotion.',
    'desk',
  ),
  entry(
    'database',
    'Office archive',
    'Atomic SQLite persistence',
    'Archive filing cabinet',
    'Files committed work and its audit entry together.',
    'Atomic local write with the corresponding ledger record.',
    'archive',
  ),
  entry(
    'checkpoint',
    'Archive box',
    'Hashed workspace checkpoint',
    'Dated archive box',
    'Preserves the exact recorded office state.',
    'Checkpoint content hash and anchored ledger event.',
    'recorder',
  ),
  entry(
    'replay',
    'Office projector',
    'Deterministic historical replay',
    'Projector and time reel',
    'Reconstructs recorded state and events at the selected time.',
    'Fixed recording bounds, recorded frame, checkpoint, and event sequence.',
    'recorder',
  ),
  entry(
    'audit',
    'Chain of custody',
    'Hash-chained event ledger',
    'Numbered archive register',
    'Shows which recorded operation caused each visible action.',
    'Sequence, timestamp, previous hash, payload hash, and verification report.',
    'recorder',
  ),
  entry(
    'gaps',
    'Missing reel marker',
    'Absent frames or legacy unverified history',
    'Explicit gap on the time reel',
    'Shows missing or unverified coverage instead of inventing a scene.',
    'Coverage report, legacy status, and first/last recorded bounds.',
    'recorder',
  ),
  entry(
    'restore',
    'Reopen an archive box',
    'Local checkpoint restore',
    'Reopened archive box',
    'Restores local workspace state after preserving the current checkpoint.',
    'Restore record; completed external actions are not undone.',
    'recorder',
  ),
];

export function officeAnalogyForTool(toolName: string): OfficeToolAnalogy | undefined {
  const exact = OFFICE_TOOL_ATLAS.find((item) => item.toolNames.includes(toolName));
  return (
    exact ??
    (toolName.startsWith('mcp_') || toolName.startsWith('integration_')
      ? OFFICE_TOOL_ATLAS.find((item) => item.id === 'integration')
      : undefined)
  );
}
