import { contextBridge, ipcRenderer } from 'electron';
import type { DesktopAPI } from '../shared/types';
const api: DesktopAPI = {
  officeRecordingBounds: () => ipcRenderer.invoke('office:recording-bounds'),
  officeReplay: (at) => ipcRenderer.invoke('office:replay', at),
  exportOfficeAudit: () => ipcRenderer.invoke('office:audit-export'),
  onAgentSession: (listener) => {
    const receive = (_event: Electron.IpcRendererEvent, update: Parameters<typeof listener>[0]) => listener(update);
    ipcRenderer.on('agent:session', receive);
    return () => ipcRenderer.removeListener('agent:session', receive);
  },
  inspectAgent: (employeeId) => ipcRenderer.invoke('agent:inspect', employeeId),
  sendAgentMessage: (input) => ipcRenderer.invoke('agent:message', input),
  saveAgentMemory: (input) => ipcRenderer.invoke('agent:memory-save', input),
  approveAgentMemory: (input) => ipcRenderer.invoke('agent:memory-approve', input),
  forgetAgentMemory: (input) => ipcRenderer.invoke('agent:memory-forget', input),
  readAgentArtifact: (input) => ipcRenderer.invoke('agent:artifact', input),
  recordFrame: (frame) => ipcRenderer.invoke('office:frame', frame),
  frameAt: (time) => ipcRenderer.invoke('office:frame-at', time),
  history: () => ipcRenderer.invoke('history:list'),
  historyState: (id) => ipcRenderer.invoke('history:state', id),
  restoreHistory: (id) => ipcRenderer.invoke('history:restore', id),
  checkpoint: () => ipcRenderer.invoke('history:checkpoint'),
  activity: () => ipcRenderer.invoke('activity:list'),
  exportActivity: (format) => ipcRenderer.invoke('activity:export', format),
  needsStorageSetup: () => ipcRenderer.invoke('storage:needs-setup'),
  useDefaultStorage: () => ipcRenderer.invoke('storage:use-default'),
  storageLocation: () => ipcRenderer.invoke('storage:location'),
  chooseDatabaseFolder: () => ipcRenderer.invoke('storage:choose'),
  integrations: () => ipcRenderer.invoke('integrations:list'),
  saveIntegration: (input) => ipcRenderer.invoke('integrations:save', input),
  removeIntegration: (id) => ipcRenderer.invoke('integrations:remove', id),
  configureOpenAI: (input) => ipcRenderer.invoke('openai:configure', input),
  microphonePermission: () => ipcRenderer.invoke('microphone:permission'),
  transcribe: (input) => ipcRenderer.invoke('voice:transcribe', input),
  broadcast: (text) => ipcRenderer.invoke('cloud:broadcast', text),
  cancelSession: (id) => ipcRenderer.invoke('cloud:cancel', id),
  localCommand: (command) => ipcRenderer.invoke('local:command', command),
  loadState: () => ipcRenderer.invoke('workspace:load'),
  saveState: (state) => ipcRenderer.invoke('workspace:save', state),
  selectFolder: () => ipcRenderer.invoke('folder:select'),
  exportDocument: (input) => ipcRenderer.invoke('document:export', input),
  getCloudSettings: () => ipcRenderer.invoke('cloud:settings'),
  configureCloud: (input) => ipcRenderer.invoke('cloud:configure', input),
  disconnectCloud: () => ipcRenderer.invoke('cloud:disconnect'),
  startSession: (input) => ipcRenderer.invoke('cloud:start', input),
  getSession: (id) => ipcRenderer.invoke('cloud:session', id),
  decideSession: (input) => ipcRenderer.invoke('cloud:decide', input),
};
contextBridge.exposeInMainWorld('ahq', api);
